// <auto-generated />
using System;
using ConstrutoraApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstrutoraApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108181741_AddFormaPagamentoToCusto")]
    partial class AddFormaPagamentoToCusto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConstrutoraApp.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF_CNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Comprador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataContrato")
                        .HasColumnType("datetime");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("longtext");

                    b.Property<int>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId")
                        .IsUnique();

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Custo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataVencimentoBoleto")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataVencimentoParcela")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("int");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumeroParcelas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorParcela")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId");

                    b.ToTable("Custos");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Empreendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorPrevisto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorRealizado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Empreendimentos");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("int");

                    b.Property<int?>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId");

                    b.HasIndex("ImovelId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Andar")
                        .HasColumnType("int");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Metragem")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<int>("Quartos")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Empreendimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Contrato", b =>
                {
                    b.HasOne("ConstrutoraApp.Models.Imovel", "Imovel")
                        .WithOne("Contrato")
                        .HasForeignKey("ConstrutoraApp.Models.Contrato", "ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Custo", b =>
                {
                    b.HasOne("ConstrutoraApp.Models.Empreendimento", "Empreendimento")
                        .WithMany("Custos")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Entrada", b =>
                {
                    b.HasOne("ConstrutoraApp.Models.Empreendimento", "Empreendimento")
                        .WithMany("Entradas")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstrutoraApp.Models.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empreendimento");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Imovel", b =>
                {
                    b.HasOne("ConstrutoraApp.Models.Empreendimento", "Empreendimento")
                        .WithMany("Imoveis")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Empreendimento", b =>
                {
                    b.Navigation("Custos");

                    b.Navigation("Entradas");

                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("ConstrutoraApp.Models.Imovel", b =>
                {
                    b.Navigation("Contrato");
                });
#pragma warning restore 612, 618
        }
    }
}
